### PR TITLE
8.0.0 update

### PR DESCRIPTION
**Pull request by fabiojgrocha**
Hi all,

I've executed the script to update to version 8.0.0 and updated the Readme file.
Seems to be working correctly, but let me know if something else is needed.

Thank you

### CODE REVIEW

**Comment by crow** [comment]
There are some additional changes that need to be made to the repo that the script isn't currently capable of making. These changes should be released soon. Thank you for the pull request though, community participation is always welcome.

**Comment by fabiojgrocha** [comment]
Any idea on when that will be ready? We need ASAP, that is why I attempted to create it myself.
Otherwise I might have to think on another solution that is not cocoapods to import this in.

**Comment by rlepinski** [comment]
We are tying our best to get it out today. The new extension has complicated things a bit, but we think we have figured it out.

**Comment by fabiojgrocha** [comment]
@rlepinski Thank you! Really appreciated!

**Comment by crow** [comment]
UrbanAirship-iOS-SDK and UrbanAirship-iOS-AppExtensions version 8.0.0 are ready. If you have any issues don't hesitate to let us know. Thanks again.

**Comment by fabiojgrocha** [comment]
Great work guys! Thank you for the quick outcome!
It builds, I will probably do some more tests during the day and let you
know how it goes!

2016-09-13 2:43 GMT+02:00 David Crow <notifications@github.com>:

**Pull request closed without merging**
